[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
bincode.workspace = true
serde.workspace = true
serde_derive.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true